name: Bingo
version: ${project.version}
main: de.coolepizza.bingo.Bingo
api-version: 1.16
load: STARTUP
commands:
  bingo:
  top:
  globalchat:
    aliases: [gc]
  reset:
    permission: bingo.admin
  backpack:
    aliases: bp
  start:
    permission: bingo.admin
  teamtp:
    aliases: ttp
